#!/bin/bash

### Container information
#Paths
DOCKER_ROOT="/var/www/nailgun/docker"
IMAGE_DIR="${docker_root}/images"
SOURCE_DIR="${docker_root}/sources"
SUPERVISOR_CONF_DIR="${docker_root}/supervisor.d"

#Version of Fuel to deploy
VERSION="5.0"
IMAGE_PREFIX="fuel"
# busybox image for storage containers
BUSYBOX_IMAGE="busybox.tar.gz"
# base centos image for all containers
BASE_IMAGE="centos.tar.gz"

# source images for apps
declare -A SOURCE_IMAGES
SOURCE_IMAGES['cobbler']="${IMAGE_DIR}cobbler"
SOURCE_IMAGES['postgres']="${IMAGE_DIR}postgres"
SOURCE_IMAGES['cobbler']="${IMAGE_DIR}rabbitmq"
SOURCE_IMAGES['rsync']="${IMAGE_DIR}rsync"
SOURCE_IMAGES['astute']="${IMAGE_DIR}astute"
SOURCE_IMAGES['nailgun']="${IMAGE_DIR}nailgun"
SOURCE_IMAGES['ostf']="${IMAGE_DIR}ostf"
SOURCE_IMAGES['nginx']="${IMAGE_DIR}nginx"

# app container names
declare -A CONTAINER_NAMES
prefix="fuel-core-${version}-"
CONTAINER_NAMES['cobbler']="${prefix}cobbler"
CONTAINER_NAMES['postgres']="${prefix}postgres"
CONTAINER_NAMES['cobbler']="${prefix}rabbitmq"
CONTAINER_NAMES['rsync']="${prefix}rsync"
CONTAINER_NAMES['astute']="${prefix}astute"
CONTAINER_NAMES['nailgun']="${prefix}nailgun"
CONTAINER_NAMES['ostf']="${prefix}ostf"
CONTAINER_NAMES['nginx']="${prefix}nginx"

# app container options
declare -A CONTAINER_OPTIONS
base_opts="-t"
CONTAINER_OPTIONS["cobbler"]="-p 53:53/udp -p 67:67/udp -p 80:80 -p 443:443 $base_opts"
CONTAINER_OPTIONS["postgres"]="-p 5432:5432 $base_opts"
CONTAINER_OPTIONS["rabbitmq"]="-p 5672:5672 -p 4369:4369 -p 15672:15672 $base_opts"
CONTAINER_OPTIONS["rsync"]="-p 873:873 $base_opts"
CONTAINER_OPTIONS["astute"]="$base_opts"
CONTAINER_OPTIONS["nailgun"]="-p 8001:8001 $base_opts"
CONTAINER_OPTIONS["ostf"]="-p 8777:8777 $base_opts"
CONTAINER_OPTIONS["nginx"]="-p 8000:8000 -p 8080:8080 $base_opts"




# storage container names
PREFIX_STORAGE="fuel-storage-${version}-"
DUMP_CNT="${prefix}dump"
REPO_CNT="${prefix}repo"
DUMP_CNT="${prefix}puppet"

